# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=25)),
                ('property_address', models.CharField(max_length=255)),
                ('property_age', models.IntegerField()),
                ('property_price', models.IntegerField()),
            ],
        ),
    ]
