# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 04:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_facing',
            field=models.CharField(choices=[('N', 'North'), ('W', 'West'), ('E', 'East'), ('S', 'South')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_img',
            field=models.ImageField(default=datetime.datetime(2019, 3, 13, 4, 32, 22, 517681, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
