# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20190314_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='property_doc',
            field=models.FileField(blank=True, null=True, upload_to=property.models.upload_property_doc),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_img',
            field=models.ImageField(blank=True, null=True, upload_to=property.models.upload_property_images),
        ),
    ]
