# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20190316_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='property_doc',
            field=models.FileField(default=django.utils.timezone.now, upload_to=property.models.upload_property_doc),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=property.models.upload_property_images),
            preserve_default=False,
        ),
    ]
