# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20190318_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='property_doc',
            field=models.FileField(upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
