# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0008_auto_20190318_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='user_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_img',
            field=models.ImageField(upload_to=property.models.upload_property_images),
        ),
    ]
